// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Videofile() {
  return window['go']['main']['App']['Videofile']();
}

export function Volume(arg1) {
  return window['go']['main']['App']['Volume'](arg1);
}
