// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {volume} from '../models';

export function Normalize(arg1:string):Promise<volume.Volume>;

export function Videofile():Promise<string>;

export function Volume(arg1:string):Promise<volume.Volume>;
