// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Videofile():Promise<string>;

export function Volume(arg1:string):Promise<Array<string>>;
